"""Remote-sync — mirror external files to local paths via a committed lockfile.

Declares a mapping of (remote URL, local path) pairs. On `lintc check`,
fetches each remote, hashes it (SHA-256), compares against a committed
lockfile at src/data/lintc-sync.lock, and writes the file + updates the
lockfile if upstream changed.

The plugin mutates disk during `lintc check`. Drift surfaces via git
working-tree state, not lintc's exit code — review changes with
`git diff` before committing.

Disabled by default. Enable via src/data/lintc.yaml:

    check:
      plugins:
        remote-sync:
          mappings:
            - remote: https://raw.githubusercontent.com/owner/repo/main/README.md
              local: src/synced/repo.md
"""
import datetime
import hashlib
import urllib.error
import urllib.request


LOCKFILE_REL_PATH = "src/data/lintc-sync.lock"


def run(cfg, plugin_config):
    """Sync each mapping from upstream; update lockfile on drift."""
    mappings = plugin_config.get("mappings")
    if mappings is None:
        return (["remote-sync: `mappings` is required in plugin config"], [])
    if not isinstance(mappings, list):
        return (["remote-sync: `mappings` must be a list of {remote, local} dicts"], [])
    if not mappings:
        return ([], [])

    errors = []
    warnings = []

    lockfile_path = cfg.root / LOCKFILE_REL_PATH
    lock_data = _read_lockfile(lockfile_path)
    lock_modified = False

    for i, mapping in enumerate(mappings):
        if not isinstance(mapping, dict):
            errors.append(
                "remote-sync: mappings[%d] must be a dict with `remote` and `local` keys" % i
            )
            continue
        remote = mapping.get("remote")
        local = mapping.get("local")
        if not remote or not local:
            errors.append(
                "remote-sync: mappings[%d] missing required `remote` or `local`" % i
            )
            continue

        content = _fetch_url(remote)
        if content is None:
            warnings.append(
                "remote-sync: could not fetch " + remote + " — skipping " + local
            )
            continue

        new_sha = hashlib.sha256(content).hexdigest()
        entry = lock_data["entries"].get(local)

        if entry is None:
            local_full = cfg.root / local
            local_full.parent.mkdir(parents=True, exist_ok=True)
            local_full.write_bytes(content)
            lock_data["entries"][local] = {
                "remote": remote,
                "sha256": new_sha,
                "fetched_at": _now_iso(),
            }
            lock_modified = True
            warnings.append(
                "remote-sync: initial sync of " + local
                + " — review with `git diff` and commit"
            )
        elif entry.get("sha256") == new_sha:
            pass
        else:
            local_full = cfg.root / local
            local_full.parent.mkdir(parents=True, exist_ok=True)
            local_full.write_bytes(content)
            lock_data["entries"][local] = {
                "remote": remote,
                "sha256": new_sha,
                "fetched_at": _now_iso(),
            }
            lock_modified = True
            warnings.append(
                "remote-sync: synced " + local
                + " (upstream changed) — review with `git diff` and commit"
            )

    if lock_modified:
        _write_lockfile(lockfile_path, lock_data)

    return errors, warnings


def _fetch_url(url):
    req = urllib.request.Request(url, headers={
        "User-Agent": "lintc-remote-sync",
    })
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return resp.read()
    except (urllib.error.URLError, OSError):
        return None


def _read_lockfile(path):
    if not path.exists():
        return {"version": 1, "entries": {}}
    import lintc
    try:
        data = lintc.yaml_parse(path.read_text(encoding="utf-8"))
    except Exception:
        return {"version": 1, "entries": {}}
    if not isinstance(data, dict):
        return {"version": 1, "entries": {}}
    if not isinstance(data.get("entries"), dict):
        data["entries"] = {}
    data.setdefault("version", 1)
    return data


def _write_lockfile(path, lock_data):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by the lintc remote-sync plugin.",
        "# Commit this file. Do not edit manually.",
        "version: " + str(lock_data.get("version", 1)),
        "entries:",
    ]
    for local in sorted(lock_data["entries"].keys()):
        entry = lock_data["entries"][local]
        lines.append("  " + _quote_yaml_key(local) + ":")
        lines.append("    remote: " + _quote_yaml_str(entry["remote"]))
        lines.append("    sha256: " + entry["sha256"])
        lines.append("    fetched_at: " + entry["fetched_at"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _quote_yaml_key(s):
    if any(c in s for c in [":", "#", "{", "}", "[", "]", "&", "*", "!", "|", ">", "'", '"', "%", "@", "`"]):
        return '"' + s.replace('"', '\\"') + '"'
    return s


def _quote_yaml_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _now_iso():
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
